# Generated by Django 6.0 on 2026-03-22 12:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_account", models.CharField(max_length=50)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("ADULT", "Adult"), ("CHILD", "Child")],
                        default="ADULT",
                        max_length=10,
                    ),
                ),
                (
                    "account_creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="The opening balance cannot be negative."
                            )
                        ],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "user")},
            },
        ),
        migrations.CreateModel(
            name="SavingsAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saving_name", models.CharField(max_length=50)),
                (
                    "saving_type",
                    models.CharField(
                        choices=[
                            ("DEPOSITS", "DEPOSITS"),
                            ("FUNDS", "FUNDS"),
                            ("RETIREMENT", "RETIREMENT"),
                            ("OTHER", "OTHER"),
                        ],
                        default="LOKATY",
                        max_length=10,
                    ),
                ),
                (
                    "saving_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("interest_rate", models.FloatField(default=0.01)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("CAR", "CAR"),
                            ("APARTMENT", "APARTMENT"),
                            ("TRAVEL", "TRAVEL"),
                            ("ENTERTAINMENT", "ENTERTAINMENT"),
                            ("EDUCATION", "EDUCATION"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("target_balance", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.01, message="The amount must be greater than zero."
                            )
                        ],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("IN", "Income"), ("OUT", "Outcome")],
                        default="OUT",
                        max_length=3,
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="budget.bankaccount",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
