# Generated by Django 6.0 on 2026-02-08 10:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="balance",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="initial_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="The opening balance cannot be negative."
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="savingsaccount",
            name="saving_type",
            field=models.CharField(
                choices=[
                    ("DEPOSITS", "DEPOSITS"),
                    ("FUNDS", "FUNDS"),
                    ("RETIREMENT", "RETIREMENT"),
                    ("OTHER", "OTHER"),
                ],
                default="LOKATY",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.01, message="The amount must be greater than zero."
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("CAR", "CAR"),
                            ("APARTMENT", "APARTMENT"),
                            ("TRAVEL", "TRAVEL"),
                            ("ENTERTAINMENT", "ENTERTAINMENT"),
                            ("EDUCATION", "EDUCATION"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("target_balance", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
