# Generated by Django 6.0 on 2026-03-28 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingsaccount",
            name="interest_rate",
            field=models.FloatField(
                default=0.01, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="savingsaccount",
            name="saving_type",
            field=models.CharField(
                choices=[
                    ("DEPOSITS", "DEPOSITS"),
                    ("FUNDS", "FUNDS"),
                    ("RETIREMENT", "RETIREMENT"),
                    ("OTHER", "OTHER"),
                ],
                default="DEPOSITS",
                max_length=10,
            ),
        ),
    ]
