# Generated by Django 6.0 on 2026-03-28 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="budget.bankaccount",
                verbose_name="Parent Account",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="initial_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name="bankaccount",
            unique_together={("user", "name_account")},
        ),
    ]
