# Generated by Django 6.0 on 2026-04-05 20:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='budget.bankaccount', verbose_name='Parent Account'),
        ),
        migrations.AddField(
            model_name='target',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='target',
            name='target_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budget.target'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='interest_rate',
            field=models.FloatField(default=0.01, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='saving_type',
            field=models.CharField(choices=[('DEPOSITS', 'DEPOSITS'), ('FUNDS', 'FUNDS'), ('RETIREMENT', 'RETIREMENT'), ('OTHER', 'OTHER')], default='DEPOSITS', max_length=10),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.category'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('user', 'name_account')},
        ),
    ]
