# Generated by Django 6.0 on 2026-01-14 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('food', 'Food'), ('home', 'Home'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('life', 'Life'), ('shopping', 'Shopping'), ('bills', 'Bills'), ('investments', 'Investments')], default='food', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('account_id', models.IntegerField()),
            ],
        ),
    ]
