# Generated by Django 6.0 on 2026-01-25 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="balance",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="initial_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="The opening balance cannot be negative."
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.01, message="The amount must be greater than zero."
                    )
                ],
            ),
        ),
    ]
