# Generated by Django 6.0 on 2026-04-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_savingsaccount_interest_rate_and_more'),
        ('budget', '0002_bankaccount_parent_alter_bankaccount_initial_balance_and_more'),
    ]

    operations = [
    ]
