# Generated by Django 6.0 on 2026-04-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_merge_20260404_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='target',
            name='target_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
