# Generated by Django 6.0 on 2026-01-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0003_category_alter_expense_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Login",
        ),
    ]
