# Generated by Django 6.0 on 2026-04-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_target_current_amount_target_target_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='target_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
