# Generated by Django 6.0 on 2026-01-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FD', 'Food'), ('HM', 'Home'), ('TP', 'Transport'), ('ET', 'Entertainment'), ('LI', 'Life'), ('SH', 'Shopping'), ('BL', 'Bills'), ('IM', 'Investments'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
