# Generated by Django 6.0 on 2026-01-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_expense_user'),
        ('budget', '0006_remove_expense_account_id_expense_user'),
    ]

    operations = [
    ]
